### PR TITLE
Development snapshot

### PR DESCRIPTION
**Pull request by ld-archer**
Creating this to pull development onto main. As last time I think we should all run a few local test runs (probably a good idea to run everything at least once; SF12 baseline and interventions, scotland mode, cross-validation).

**Changes:**
- Longitudinal GEE models
- Yeo Johnson transformation
- Cross-validation improvements (5-fold)
- Population inflation infrastructure
- SIPHER 7 Equivalent Income experiment
- Additional logging in output directory logs
- Heating and Financial situation modules added
- Fertility module improvements including parity
- Updated to add wave 12 of US and change starting year
- Scotland population and interventions
- Visualisation by additional subgroups added (vulnerable groups)
- More?

### CODE REVIEW

**Comment by paddy-r** [comment]
Running some scenarios...

1. ```make baseline_default```: all good, same for ```make test_run```
2. ```make intervention_hhIncome```: issue with config/mode

```
python scripts/run.py -c  -o scotland_mode -i 'hhIncomeIntervention'
usage: use "run.py --help" for more information
run.py: error: argument -c/--config: expected one argument
make: *** [scripts/Makefile:46: intervention_hhIncome] Error 2
```

Easily fixed with (say) ```$(PYTHON) scripts/run.py -c $(CONFIG)/default.yaml -o default_config -i 'hhIncomeIntervention'```, but flagging anyway.

3. ```make scot_setup``` then ```make test_run_scot```: all good
4. ```make cv_setup```: path issue, last part of output below

```
  File "<path removed>/minos/Minos/minos/data_generation/US_utils.py", line 28, in check_output_dir
    os.mkdir(output)
FileNotFoundError: [Errno 2] No such file or directory: 'data/final_US/cross_validation/transition/'
make: *** [minos/data_generation/Makefile:71: <path removed>/minos/Minos/data/final_US/cross_validation/transition/2020_US_cohort.csv] Error 1
```

Not able to diagnose that one, seems to be 2020-specific.

**Review by paddy-r — CHANGES_REQUESTED** [review]
Running some scenarios...

1. ```make baseline_default```: all good, same for ```make test_run```
2. ```make intervention_hhIncome```: issue with config/mode

```
python scripts/run.py -c  -o scotland_mode -i 'hhIncomeIntervention'
usage: use "run.py --help" for more information
run.py: error: argument -c/--config: expected one argument
make: *** [scripts/Makefile:46: intervention_hhIncome] Error 2
```

Easily bodged with (say) ```$(PYTHON) scripts/run.py -c $(CONFIG)/default.yaml -o default_config -i 'hhIncomeIntervention'```, but flagging anyway.

3. ```make scot_setup``` then ```make test_run_scot```: all good
4. ```make cv_setup```: path issue, last part of output below

```
  File "<path removed>/minos/Minos/minos/data_generation/US_utils.py", line 28, in check_output_dir
    os.mkdir(output)
FileNotFoundError: [Errno 2] No such file or directory: 'data/final_US/cross_validation/transition/'
make: *** [minos/data_generation/Makefile:71: <path removed>/minos/Minos/data/final_US/cross_validation/transition/2020_US_cohort.csv] Error 1
```

~~Not able to diagnose that one, seems to be 2020-specific.~~ Can be fixed by replacing ```mkdir``` with ```makedirs``` in ```US_utils.check_output_dir```.

**Comment by ld-archer** [comment]
Hey Hugh, just responding to your review comment above (can't figure out how to just reply directly so I'm putting it here). The error you were getting above is due to the way the make targets are set up. The config file is an argument that has to be set when running the make targets, which unfortunately means if you run the wrong target (or try to run one directly) you will hit this error. If you run `make all_scenarios`, this is a combined target that sets the config as `default_config.yaml` and runs baseline and all interventions. This is unfortunate but the alternative is to have a different set of intervention targets for each config (at the moment we have default, SIPHER7, scotland_mode (not used much if at all anymore), and inflated_default (new). We need to address this at some point, but will need a bit of a discussion and a bit of time to plan it I think. I don't think it should stop this snapshot from being pushed to main. (The way around this when I want to test a single intervention is to just manually change the config argument from $(RUN_CONFIG) to whatever config I need, and the same with the $(MODE) argument for naming the output directory).

**Comment by paddy-r** [comment]
> Hey Hugh, just responding to your review comment above (can't figure out how to just reply directly so I'm putting it here). The error you were getting above is due to the way the make targets are set up. The config file is an argument that has to be set when running the make targets, which unfortunately means if you run the wrong target (or try to run one directly) you will hit this error. If you run `make all_scenarios`, this is a combined target that sets the config as `default_config.yaml` and runs baseline and all interventions. This is unfortunate but the alternative is to have a different set of intervention targets for each config (at the moment we have default, SIPHER7, scotland_mode (not used much if at all anymore), and inflated_default (new). We need to address this at some point, but will need a bit of a discussion and a bit of time to plan it I think. I don't think it should stop this snapshot from being pushed to main. (The way around this when I want to test a single intervention is to just manually change the config argument from `$(RUN_CONFIG)` to whatever config I need, and the same with the `$(MODE)` argument for naming the output directory).

No worries, that review is outdated anyway, please ignore!

**Comment by ld-archer** [comment]
May have just thought of a fix for it anyway, just testing will push if it works.

**Review by paddy-r — APPROVED** [review]

**Comment by RobertClay** [comment]
does this still want reviewing?

**Pull request merged**
