### PR TITLE
166 sphinx tweaks

### PR DESCRIPTION
**Pull request by RobertClay**
Updating sphinx docs to do some tidying and match new development branch.
- Run relative to top level of MINOS. Was originally running from /docsrc which made tending data file paths confusing. Everything should run from the top level now.
- Remove test directory. Uses transition models generated by estimate_transitions.R now.
- Update estimate_transitons.R slightly to include outcome variable as an attribute of model objects. Allows for post-hoc plotting without the original data frame. Saves space and allows for plotting in sphinx (observed vs predicted at least) just using model RDS files. May need to add more variables later for disaggregated plots.. 
- Remove labour module page. Not used for now and slow to generate..
- Update environment yaml to include required sphinx packages.
- docsrc make clean command that clears /docs folder except for .nojekyll that is needed for readthedocs styling to work. Useful when adding or removing new parts of the website to ensure they are correctly rendered. May make this a requirement for make github..
- Remove some deprecated junk files in /docsrc.

### CODE REVIEW

**Comment by ld-archer** [comment]
The changes look good when I look at the files directly but the docs haven't been updated at the link. Does Sphinx only draw from a specific branch? Will this update when this PR is merged or do we need to run the make targets?

**Comment by RobertClay** [comment]
If you go into settings/pages it shows which branch the website is built from. It is currently built from development and wont be updated until 166 branch is pulled in. We can run the github page from the 166 branch instead if you'd like to test before pulling.

**Review by ld-archer — APPROVED** [review]
Brilliant stuff, and no don't worry about changing the branch I just wanted to confirm. I can see the changes in the commits and they all look good so I'm happy enough.

**Comment by RobertClay** [comment]
changes are active now. Cant see any glaring issues.

**Pull request merged**
