### PR TITLE
291 tidy up component priorities

### LINKED ISSUE #291: Tidying up component priorities throughout pipeline
During #259, disparity between priority of components came up and need to be fixed. Stages in pipeline are:

1. User specifies components to be included in simulation in config file.
2. The order of components is then determined automatically via a dictionary in ```RunPipeline```, as of [019cb4c](https://github.com/Leeds-MRG/Minos/pull/259/commits/019cb4c99756bc491ad8040b2782d9c27c8f4c90), [be59252](https://github.com/Leeds-MRG/Minos/pull/259/commits/be59252fd0b968d39d8b0284826a3f1bb4da8529), etc., in #259.
3. Components are then also assigned priorities during initialisation within their ```setup``` method in the ```builder.event.register_listener``` line, but these priorities don't always match those in ```RunPipeline```.

Want to make sure:

* [x] Priorities in ```RunPipeline``` and setup methods match.
* [x] Mortality higher priority than fertility to avoid killing new mothers.
* [x] Order should be:

0. Replenishment
1. Mortality
2. Fertility
3. Education
4. Intervention (all classes in ```intervention.py```)
5. Income (all classes in ```income.py```)
6. All other pathways (e.g. housing, neighbourhood, tobacco)
7. ...except mental wellbeing (all classes in ```mental_wellbeing.py```), which comes last here

* [x] For SIPHER7 variables (anything beginning with ```S7_```) apply priority = 6 except equivalent income which is 7.
* [x] Income modules need to be corrected as properly specified in ```RunPipeline``` priority dict (e.g. was ```geeIncome```, should be ```geeIncome()```).

N.B. Not changing ```base_population``` priority as doesn't seem to be used. Noting here for posterity.

### PR DESCRIPTION
**Pull request by paddy-r**

### CODE REVIEW

**Comment by paddy-r** [comment]
Sorry about this, @RobertClay. Should have made sure this was merged months ago. It's mainly just changing module priorities based on discussions we had.

**Comment by paddy-r** [comment]
Converting to draft as needs more work; see #291.

**Comment by paddy-r** [comment]
@RobertClay Think this is ready. `JobSec`, `JobHours` and `HourlyWage` moved to the same priority as income, but can move if that's not the best place for them. `Education` is on its own (which I think may be a legacy of when we talked about it last year, so can also moved if it's better elsewhere).

**Comment by RobertClay** [comment]
all makes sense to me.

**Comment by RobertClay** [comment]
one thing that may be useful is assigning the priority levels somewhere in US_utils rather than trying to keep track of them all manually.

**Review by RobertClay — APPROVED** [review]

**Comment by paddy-r** [comment]
> one thing that may be useful is assigning the priority levels somewhere in US_utils rather than trying to keep track of them all manually.

Okay, will roll that over into another issue to get this one done forever. See #378.

**Pull request merged**
