### PR TITLE
389 standardise lookups

### LINKED ISSUE #389: Standardise LSOA to LA lookups everywhere
Prompted by #322 and #384, there's more than one lookup file being used for EWS LSOAs/DZs to LA lookups. E.g. using 2022 LA definitions in #322 but 2017 definitions in #384. Also some 2018 definitions being used in `data_generation.UK_area_code_JSONs`, although there might be good reasons for doing this!

However, flagging it in case we want to standardise it everywhere, with a view to just updating the reference file and headers in a single place in the future as we move to (e.g.) 2023 definitions, which was a major change.

See here for details: https://en.wikipedia.org/wiki/2023_Periodic_Review_of_Westminster_constituencies.

### PR DESCRIPTION
**Pull request by paddy-r**

### CODE REVIEW

**Comment by paddy-r** [comment]
Already merged #384 into this, BTW.

**Comment by paddy-r** [comment]
Set to draft for now, as may need further work if we want a single method everywhere, e.g. 2017 and 2018 LA definitions mentioned in `data_generation.UK_area_code_JSONs`. And already merged with #322/#388.

**Comment by paddy-r** [comment]
@RobertClay ready to merge, but are there any other places where the reference year needs changing, and do we actually want a single reference year (2022 in what I've done here and elsewhere) throughout Minos? If not, and if what's here is sufficient for now, I'll merge this and start a fresh issue if necessary.

**Review by RobertClay — APPROVED** [review]
not sure what you mean by reference year. if you think it shouldn't be harded coded maybe put it in the yaml config?

**Comment by paddy-r** [comment]
> not sure what you mean by reference year. if you think it shouldn't be harded coded maybe put it in the yaml config?

I just mean which year's LA definitions we use, as they change every year, e.g. those in `data_generation.UK_area_code_JSONs` are 2017/2018 are different from the 2022 LAs in this PR.

**Pull request merged**
