### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ld-archer**
Merging development onto main to keep a working snapshot of the code at this point. Many many changes since the last main state, here is a quick rundown of big changes:

- Big expansion to the Sphinx documentation, including much more information on each module and details on the transition models and composite variables.
- Updated transition estimation to use the model_definitions.txt file for quick modification of transition models.
- Updated the transition models with recommendations from SIPHER colleagues.
- Improved generation of some composite variables, with more even groups and better handling of missing values.
- Created new composite variables for household composition, physical health, marital status
- Scripts and associated make commands for running with slurm on the beefy machine.
- Added Windows utils to enable proper development on Windows OS
- Refactored modules.r_utils functions to be generic, with a function for each type of transition model
- Added multiprocessing for aggregate_minos_output work on batch runs
- Updated tobacco model, and better handling of deterministic missing values of ncigs
- Updated title and axis labels for lineplots
- Changed model to start in 2017 as this is last year with full information for all SF12 predictor variables
- Implemented 'next_{var}' functionality for transition models to ensure predicting with lagged values is correct
- Added NoReplenishment and new fertility modules
- Changed replenishing populations to take 16 & 17 year olds from 2017 to add each year. All new simulants are age 16, but using the 17s as well meant more heterogeneity in replenishing pops and maintains the age structure over time.
- Added a 'Scotland mode' for running only with a Scottish subsample from US (still rough in this version - WIP)
- Stopped scaling all continuous variables in the model definition formulas
- Vastly simplified and improved the setup and install process for Vivarium and other dependencies using conda environment.yml file
- Fix interventions by not resetting hh_income values at each wave

If theres anything missing from this list please add to it!

Also reviewers please comment when you've tested the new development and are happy to merge.

### CODE REVIEW

**Review by paddy-r — CHANGES_REQUESTED** [review]
Tested by creating new environment from scratch (Python 3.9, R 4.1.3 as in makefile), then make setup -> baseline -> aggregate_baseline_map to ensure all R packages are called. All good, except required argument "-u" to ```make aggregate_baseline_map``` not specified in makefile, so raises error. Argument also absent in other "aggregate" targets.


Workaround by changing line in ```format_spatial_output.py```: changed
```
parser.add_argument("-u", "--subset_function", required=True, type=str,
```
to
```
parser.add_argument("-u", "--subset_function", type=str, default=None,
```
for the sake of producing a map, but maybe not a good fix in general!

**Comment by paddy-r** [comment]
> Tested by creating new environment from scratch (Python 3.9, R 4.1.3 as in makefile), then make setup -> baseline -> aggregate_baseline_map to ensure all R packages are called. All good, except required argument "-u" to `make aggregate_baseline_map` not specified in makefile, so raises error. Argument also absent in other "aggregate" targets.
> 
> Workaround by changing line in `format_spatial_output.py`: changed
> 
> ```
> parser.add_argument("-u", "--subset_function", required=True, type=str,
> ```
> 
> to
> 
> ```
> parser.add_argument("-u", "--subset_function", type=str, default=None,
> ```
> 
> for the sake of producing a map, but maybe not a good fix in general!

Fixed with #152/#153, all good to merge.

**Review by paddy-r — APPROVED** [review]

**Review by RobertClay — APPROVED** [review]
test run succesful. plots looking good.

**Comment by paddy-r** [comment]
OMG

**Pull request merged**
