### PR TITLE
revert to older locf logic. dunno why this version of LOCF is in dev..

### LINKED ISSUE #451: Number of kids not retained at final US stage
Need well populated `nkids_ind` for fertility development/write-up but only ~10% retained on `369-noparity` (branched off `development`) currently at `final_us` stage. Checked back to `226-add-parity-to-fertility-module` and `nkids_ind` looks to be fully populated, so must be changes made since then.

### PR DESCRIPTION
**Pull request by RobertClay**
reverted to older version of LOCF logic. no clue why this experimental version was in dev. model runs all the way through. could do with other testing and handovers as well.

### CODE REVIEW

**Comment by RobertClay** [comment]
working all the way through now. @paddy-r  please test.

**Comment by paddy-r** [comment]
@RobertClay data generation looks good for me. Jimmy's back.

Looking at 2020 US final data, with `final20.nkids_ind.value_counts(normalize=True, dropna=False).sort_index()`:

image

Anything else I can test?

**Comment by RobertClay** [comment]
full model run and handovers. see if this fixes child ages.

**Comment by paddy-r** [comment]
Handovers looks good to me, so I'm happy if you're happy.

image

image

**Comment by paddy-r** [comment]
Here's child ages, although I'm not au fait with that, or what the issue was...

image

image

image

**Comment by RobertClay** [comment]
All looks sensible. Will merge unless any objections @ld-archer .

**Comment by ld-archer** [comment]
All looks good to me, haven't tested but happy if you have.

**Pull request merged**
