### PR TITLE
395 update python

### PR DESCRIPTION
**Pull request by RobertClay**
see #392 updating data generation pipeline to 3.11 without any warnings. works on both 3.7 and 3.11. 

conda env for python 3.11 and conda 4.3.3 thats stable. need to debug the whole vivarium model run later in another issue.

### CODE REVIEW

**Comment by paddy-r** [comment]
@RobertClay Got so far but no further.

1. Get a wall of deprecation warnings from `data_generation.US_missing_LOCF`, lines 47 and 75: `FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`. I seem to remember it already being flagged elsewhere... 

2. Get a `ModuleNotFoundError` for `minos` when running `make setup` (via `make baseline`) for the first time after creating the 3.11 environment. It's present with `conda list` but not `pip list`. Solved by manually running `pip install -v -e .`, after which it's also present with `pip list`. Maybe check to see if you get the same issue.

3. I get a wall of `FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!` warnings during `US_complete_case` and `generate_stock_pop`.

4. Added `r-lme4` to env file (was commented out and thus caused module error). See [e3dfffe](https://github.com/Leeds-MRG/Minos/pull/424/commits/e3dfffe295c4b55c1ac629b9a381c666e9505036).

Couldn't get beyond this point:
```
[1] "Estimating transition models in whole population mode"
[1] "Starting for hh_income..."
Error in initializePtr() :
  function 'chm_factor_ldetL2' not provided by package 'Matrix'
Calls: run_longitudinal_models ... initialize -> <Anonymous> -> initializePtr -> .Call
Execution halted
make: *** [minos/transitions/Makefile:28: <PATH REMOVED>/minos/Minos/data/transitions/SF_12/glmm/SF_12_GLMM.rds] Error 1
```

EDIT: All fixed in [7f11f33](https://github.com/Leeds-MRG/Minos/pull/424/commits/7f11f330dac88aa2d673bbded22262aa1ce49cee)

**Comment by RobertClay** [comment]
closing this at it seems like more work than its worth. a lot of changes in new vivarium that will require bashing heads into walls most likely.

**Comment by paddy-r** [comment]
For posterity in case we revisit in the future, another strategy might have been to update incrementally, as the remaining version zeroes of Vivarium (i.e. all before v1.0.0) look to be largely bug fixes and relatively small changes. So, upgrade to (say) v0.10.22 (Dec 2022) and deal with any issues, then v1.0.0 (also Dec 2022), then v1.2.8 (Sep 2023), which is one short of v2.0.0 in which the Component and Manager classes were added.

**Comment by paddy-r** [comment]
Also @RobertClay, might want to pull commit b94b5fa895992114014ff8306c8da380ece3a258 on `395-update_python` into `development` as it contains fix for education state target that doesn't exist. Issue still present as `development` doesn't currently run for me for that reason.

**Comment by RobertClay** [comment]
can we get a seperate branch with just the education fix. sorry its tedious but some stuff I'd rather not pull into dev.

**Comment by paddy-r** [comment]
@RobertClay done in #433/#434.

**Pull request closed without merging**
